services:
  go-app:
    container_name: go-app
    image: irfan/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: Arsyads698
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "3131:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:  
  pgdata: {}